version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile_judge0_api.dockerfile
    image: edyst/judge0-api:local
    volumes:
      - ${PWD}/judge0-api.conf:/judge0-api.conf
      - ${PWD}:/usr/src/api/
    ports:
      - '3000:3000'
    env_file: judge0-api.conf
    privileged: true
    restart: always

  worker:
    image: edyst/judge0-api:local
    command: ['./scripts/run-workers']
    volumes:
      - ${PWD}/judge0-api.conf:/judge0-api.conf:ro
    env_file: judge0-api.conf
    privileged: true
    depends_on:
      - api
    restart: always

  db:
    image: postgres:9.6
    env_file: judge0-api.conf
    volumes:
      - ./srv/postgres-data:/var/lib/postgresql/data/
    restart: always

  redis:
    image: redis:4.0
    command:
      [
        'bash',
        '-c',
        'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"',
      ]
    env_file: judge0-api.conf
    volumes:
      - ./srv/redis-data:/data
    restart: always
